<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            id: img
            size_hint_y: 0.8
        TextInput:
            id: user_query
            size_hint_y: 0.08
            font_size: 22
            font_family: "Arial"
        Button:
            text: "Search Image"
            size_hint_y: 0.12
            on_press: root.search_image()

<RootWidget>:
    FirstScreen:
        id: first_screen
        name: "first_screen"